// Hand-written from docs/superpowers/plans/2026-10-02-squadjar-contracts.md. Plain `as const` literals so viem infers arg/result types.

export const tokenAbi = [
  {type:"function",name:"faucet",inputs:[{name:"amount",type:"uint256"}],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"approve",inputs:[{name:"spender",type:"address"},{name:"value",type:"uint256"}],outputs:[{name:"",type:"bool"}],stateMutability:"nonpayable"},
  {type:"function",name:"allowance",inputs:[{name:"owner",type:"address"},{name:"spender",type:"address"}],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"balanceOf",inputs:[{name:"account",type:"address"}],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"FAUCET_MAX",inputs:[],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"event",name:"Transfer",anonymous:false,inputs:[{indexed:true,name:"from",type:"address"},{indexed:true,name:"to",type:"address"},{indexed:false,name:"value",type:"uint256"}]},
  {type:"error",name:"FaucetCapExceeded",inputs:[]},
  {type:"error",name:"ERC20InsufficientBalance",inputs:[{name:"sender",type:"address"},{name:"balance",type:"uint256"},{name:"needed",type:"uint256"}]},
  {type:"error",name:"ERC20InsufficientAllowance",inputs:[{name:"spender",type:"address"},{name:"allowance",type:"uint256"},{name:"needed",type:"uint256"}]},
  {type:"error",name:"ERC20InvalidSender",inputs:[{name:"sender",type:"address"}]},
  {type:"error",name:"ERC20InvalidReceiver",inputs:[{name:"receiver",type:"address"}]},
  {type:"error",name:"ERC20InvalidApprover",inputs:[{name:"approver",type:"address"}]},
  {type:"error",name:"ERC20InvalidSpender",inputs:[{name:"spender",type:"address"}]},
] as const;

export const registryAbi = [
  {type:"function",name:"trustScore",inputs:[{name:"user",type:"address"}],outputs:[{name:"",type:"int256"}],stateMutability:"view"},
  {type:"function",name:"tier",inputs:[{name:"user",type:"address"}],outputs:[{name:"",type:"uint8"}],stateMutability:"view"},
  {type:"function",name:"isSquad",inputs:[{name:"squad",type:"address"}],outputs:[{name:"",type:"bool"}],stateMutability:"view"},
  {type:"function",name:"isWriter",inputs:[{name:"factory",type:"address"}],outputs:[{name:"",type:"bool"}],stateMutability:"view"},
  {type:"error",name:"NotWriter",inputs:[]},
  {type:"error",name:"NotSquad",inputs:[]},
  {type:"function",name:"records",inputs:[{name:"",type:"address"}],outputs:[{name:"onTime",type:"uint32"},{name:"late",type:"uint32"},{name:"missed",type:"uint32"},{name:"completed",type:"uint32"}],stateMutability:"view"},
] as const;

export const factoryAbi = [
  {type:"function",name:"createSquad",inputs:[{name:"contribution",type:"uint256"},{name:"maxMembers",type:"uint8"},{name:"period",type:"uint8"},{name:"inviteHash",type:"bytes32"},{name:"firstDeadline",type:"uint64"}],outputs:[{name:"",type:"address"}],stateMutability:"nonpayable"},
  {type:"function",name:"squads",inputs:[{name:"",type:"uint256"}],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"function",name:"squadCount",inputs:[],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"registry",inputs:[],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"function",name:"token",inputs:[],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"function",name:"isSquad",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"bool"}],stateMutability:"view"},
  {type:"function",name:"timing",inputs:[{name:"p",type:"uint8"}],outputs:[{name:"roundLength",type:"uint32"},{name:"grace",type:"uint32"},{name:"depositWindow",type:"uint32"}],stateMutability:"view"},
  {type:"event",name:"SquadCreated",anonymous:false,inputs:[{indexed:true,name:"squad",type:"address"},{indexed:true,name:"organizer",type:"address"},{indexed:false,name:"contribution",type:"uint256"},{indexed:false,name:"maxMembers",type:"uint8"},{indexed:false,name:"period",type:"uint8"}]},
  {type:"event",name:"Membership",anonymous:false,inputs:[{indexed:true,name:"member",type:"address"},{indexed:true,name:"squad",type:"address"},{indexed:false,name:"joined",type:"bool"}]},
  {type:"error",name:"ContributionTooLow",inputs:[{name:"min",type:"uint256"}]},
  {type:"error",name:"SizeOutOfRange",inputs:[{name:"min",type:"uint8"},{name:"max",type:"uint8"}]},
  {type:"error",name:"EmptyInvite",inputs:[]},
  {type:"error",name:"DeadlineInPast",inputs:[]},
  {type:"error",name:"DeadlineTooFar",inputs:[]},
  {type:"error",name:"NotSquad",inputs:[]},
] as const;

export const squadAbi = [
  {type:"function",name:"getState",inputs:[],outputs:[{name:"v",type:"tuple",components:[{name:"state",type:"uint8"},{name:"contribution",type:"uint256"},{name:"maxMembers",type:"uint8"},{name:"roundLength",type:"uint32"},{name:"grace",type:"uint32"},{name:"depositDeadline",type:"uint64"},{name:"roundDeadline",type:"uint64"},{name:"currentRound",type:"uint8"},{name:"organizer",type:"address"},{name:"members",type:"address[]"},{name:"locked",type:"uint256[]"},{name:"required",type:"uint256[]"},{name:"paidThisRound",type:"bool[]"},{name:"stopped",type:"bool[]"},{name:"misses",type:"uint8[]"},{name:"refillBy",type:"uint8[]"},{name:"owed",type:"uint256[]"},{name:"countsForTrust",type:"bool"},{name:"activeCount",type:"uint8"},{name:"totalLocked",type:"uint256"},{name:"settleableAfter",type:"uint64"}]}],stateMutability:"view"},
  {type:"function",name:"contribution",inputs:[],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"paid",inputs:[{name:"round",type:"uint256"},{name:"member",type:"address"}],outputs:[{name:"",type:"bool"}],stateMutability:"view"},
  {type:"function",name:"isMember",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"bool"}],stateMutability:"view"},
  {type:"function",name:"firstDeadline",inputs:[],outputs:[{name:"",type:"uint64"}],stateMutability:"view"},
  {type:"function",name:"memberCount",inputs:[],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"memberAt",inputs:[{name:"i",type:"uint256"}],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"function",name:"inviteHash",inputs:[],outputs:[{name:"",type:"bytes32"}],stateMutability:"view"},
  {type:"function",name:"join",inputs:[{name:"code",type:"bytes32"}],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"joinWithPermit",inputs:[{name:"code",type:"bytes32"},{name:"deadline",type:"uint256"},{name:"v",type:"uint8"},{name:"r",type:"bytes32"},{name:"s",type:"bytes32"}],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"leave",inputs:[],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"remove",inputs:[{name:"m",type:"address"}],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"cancel",inputs:[],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"start",inputs:[],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"lockDeposit",inputs:[],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"finalizeDeposits",inputs:[],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"contribute",inputs:[],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"refillDeposit",inputs:[],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"settleRound",inputs:[{name:"round",type:"uint8"}],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"settleableAfter",inputs:[],outputs:[{name:"",type:"uint64"}],stateMutability:"view"},
  {type:"event",name:"Joined",anonymous:false,inputs:[{indexed:true,name:"member",type:"address"}]},
  {type:"event",name:"Left",anonymous:false,inputs:[{indexed:true,name:"member",type:"address"}]},
  {type:"event",name:"Cancelled",anonymous:false,inputs:[]},
  {type:"event",name:"Started",anonymous:false,inputs:[{indexed:false,name:"order",type:"address[]"}]},
  {type:"event",name:"DepositLocked",anonymous:false,inputs:[{indexed:true,name:"member",type:"address"},{indexed:false,name:"amount",type:"uint256"}]},
  {type:"event",name:"Dropped",anonymous:false,inputs:[{indexed:true,name:"member",type:"address"}]},
  {type:"event",name:"Activated",anonymous:false,inputs:[{indexed:false,name:"roundDeadline",type:"uint64"}]},
  {type:"event",name:"Contributed",anonymous:false,inputs:[{indexed:true,name:"member",type:"address"},{indexed:false,name:"round",type:"uint8"},{indexed:false,name:"late",type:"bool"}]},
  {type:"event",name:"RoundSettled",anonymous:false,inputs:[{indexed:false,name:"round",type:"uint8"},{indexed:true,name:"collector",type:"address"},{indexed:false,name:"amount",type:"uint256"},{indexed:false,name:"missed",type:"address[]"}]},
  {type:"event",name:"StoppedPaying",anonymous:false,inputs:[{indexed:true,name:"member",type:"address"}]},
  {type:"event",name:"Completed",anonymous:false,inputs:[]},
  {type:"error",name:"ERC20InsufficientBalance",inputs:[{name:"sender",type:"address"},{name:"balance",type:"uint256"},{name:"needed",type:"uint256"}]},
  {type:"error",name:"ERC20InsufficientAllowance",inputs:[{name:"spender",type:"address"},{name:"allowance",type:"uint256"},{name:"needed",type:"uint256"}]},
  {type:"error",name:"WrongState",inputs:[{name:"current",type:"uint8"}]},
  {type:"error",name:"NotOrganizer",inputs:[]},
  {type:"error",name:"NotMember",inputs:[]},
  {type:"error",name:"AlreadyMember",inputs:[]},
  {type:"error",name:"Full",inputs:[]},
  {type:"error",name:"OrganizerCannotLeave",inputs:[]},
  {type:"error",name:"BadInvite",inputs:[]},
  {type:"error",name:"TooFewMembers",inputs:[]},
  {type:"error",name:"NothingOwed",inputs:[]},
  {type:"error",name:"DepositWindowOpen",inputs:[]},
  {type:"error",name:"AlreadyPaid",inputs:[]},
  {type:"error",name:"PastGrace",inputs:[]},
  {type:"error",name:"MemberStoppedPaying",inputs:[]},
  {type:"error",name:"TooEarly",inputs:[{name:"settleableAfter",type:"uint64"}]},
  {type:"error",name:"RoundNotOpen",inputs:[{name:"opensAt",type:"uint64"}]},
  {type:"error",name:"AlreadySettled",inputs:[]},
  {type:"function",name:"organizer",inputs:[],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"function",name:"locked",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"required",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"owed",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"stoppedPaying",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"bool"}],stateMutability:"view"},
] as const;

