// Generated from contracts/abi/*.json (internalType dropped); token and registry are hand-picked subsets. Plain `as const` literals so viem infers arg/result types.

export const tokenAbi = [
  {type:"function",name:"faucet",inputs:[{name:"amount",type:"uint256"}],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"approve",inputs:[{name:"spender",type:"address"},{name:"value",type:"uint256"}],outputs:[{name:"",type:"bool"}],stateMutability:"nonpayable"},
  {type:"function",name:"transfer",inputs:[{name:"to",type:"address"},{name:"value",type:"uint256"}],outputs:[{name:"",type:"bool"}],stateMutability:"nonpayable"},
  {type:"function",name:"allowance",inputs:[{name:"owner",type:"address"},{name:"spender",type:"address"}],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"balanceOf",inputs:[{name:"account",type:"address"}],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"FAUCET_MAX",inputs:[],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"event",name:"Transfer",anonymous:false,inputs:[{indexed:true,name:"from",type:"address"},{indexed:true,name:"to",type:"address"},{indexed:false,name:"value",type:"uint256"}]},
  {type:"error",name:"FaucetCapExceeded",inputs:[]},
  {type:"error",name:"ERC20InsufficientBalance",inputs:[{name:"sender",type:"address"},{name:"balance",type:"uint256"},{name:"needed",type:"uint256"}]},
  {type:"error",name:"ERC20InsufficientAllowance",inputs:[{name:"spender",type:"address"},{name:"allowance",type:"uint256"},{name:"needed",type:"uint256"}]},
  {type:"error",name:"ERC20InvalidSender",inputs:[{name:"sender",type:"address"}]},
  {type:"error",name:"ERC20InvalidReceiver",inputs:[{name:"receiver",type:"address"}]},
  {type:"error",name:"ERC20InvalidApprover",inputs:[{name:"approver",type:"address"}]},
  {type:"error",name:"ERC20InvalidSpender",inputs:[{name:"spender",type:"address"}]},
] as const;

export const registryAbi = [
  {type:"function",name:"trustScore",inputs:[{name:"user",type:"address"}],outputs:[{name:"",type:"int256"}],stateMutability:"view"},
  {type:"function",name:"tier",inputs:[{name:"user",type:"address"}],outputs:[{name:"",type:"uint8"}],stateMutability:"view"},
  {type:"function",name:"isSquad",inputs:[{name:"squad",type:"address"}],outputs:[{name:"",type:"bool"}],stateMutability:"view"},
  {type:"function",name:"isWriter",inputs:[{name:"factory",type:"address"}],outputs:[{name:"",type:"bool"}],stateMutability:"view"},
  {type:"error",name:"NotWriter",inputs:[]},
  {type:"error",name:"NotSquad",inputs:[]},
  {type:"function",name:"records",inputs:[{name:"",type:"address"}],outputs:[{name:"onTime",type:"uint32"},{name:"late",type:"uint32"},{name:"missed",type:"uint32"},{name:"completed",type:"uint32"}],stateMutability:"view"},
] as const;

export const factoryAbi = [
  {type:"function",name:"MAX_FIRST_DEADLINE_DELAY",inputs:[],outputs:[{name:"",type:"uint64"}],stateMutability:"view"},
  {type:"function",name:"createSquad",inputs:[{name:"contribution",type:"uint256"},{name:"maxMembers",type:"uint8"},{name:"period",type:"uint8"},{name:"inviteHash",type:"bytes32"},{name:"firstDeadline",type:"uint64"}],outputs:[{name:"",type:"address"}],stateMutability:"nonpayable"},
  {type:"function",name:"isSquad",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"bool"}],stateMutability:"view"},
  {type:"function",name:"noteMembership",inputs:[{name:"member",type:"address"},{name:"joined",type:"bool"}],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"registry",inputs:[],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"function",name:"squadCount",inputs:[],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"squads",inputs:[{name:"",type:"uint256"}],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"function",name:"timing",inputs:[{name:"p",type:"uint8"}],outputs:[{name:"roundLength",type:"uint32"},{name:"grace",type:"uint32"}],stateMutability:"pure"},
  {type:"function",name:"token",inputs:[],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"event",name:"Membership",inputs:[{name:"member",type:"address",indexed:true},{name:"squad",type:"address",indexed:true},{name:"joined",type:"bool",indexed:false}],anonymous:false},
  {type:"event",name:"SquadCreated",inputs:[{name:"squad",type:"address",indexed:true},{name:"organizer",type:"address",indexed:true},{name:"contribution",type:"uint256",indexed:false},{name:"maxMembers",type:"uint8",indexed:false},{name:"period",type:"uint8",indexed:false}],anonymous:false},
  {type:"error",name:"ContributionTooLow",inputs:[{name:"min",type:"uint256"}]},
  {type:"error",name:"DeadlineInPast",inputs:[]},
  {type:"error",name:"DeadlineTooFar",inputs:[]},
  {type:"error",name:"EmptyInvite",inputs:[]},
  {type:"error",name:"NotSquad",inputs:[]},
  {type:"error",name:"SizeOutOfRange",inputs:[{name:"min",type:"uint8"},{name:"max",type:"uint8"}]},
] as const;

export const squadAbi = [
  {type:"function",name:"BUILDING",inputs:[],outputs:[{name:"",type:"uint8"}],stateMutability:"view"},
  {type:"function",name:"RELIABLE",inputs:[],outputs:[{name:"",type:"uint8"}],stateMutability:"view"},
  {type:"function",name:"TRUST_MIN_CONTRIBUTION",inputs:[],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"TRUST_MIN_MEMBERS",inputs:[],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"TRUST_MIN_ROUND_LENGTH",inputs:[],outputs:[{name:"",type:"uint32"}],stateMutability:"view"},
  {type:"function",name:"allowanceOf",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"uint8"}],stateMutability:"view"},
  {type:"function",name:"cancel",inputs:[],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"contribute",inputs:[],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"contribution",inputs:[],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"countsForTrust",inputs:[],outputs:[{name:"",type:"bool"}],stateMutability:"view"},
  {type:"function",name:"credit",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"currentRound",inputs:[],outputs:[{name:"",type:"uint8"}],stateMutability:"view"},
  {type:"function",name:"factory",inputs:[],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"function",name:"firstDeadline",inputs:[],outputs:[{name:"",type:"uint64"}],stateMutability:"view"},
  {type:"function",name:"getState",inputs:[],outputs:[{name:"v",type:"tuple",components:[{name:"state",type:"uint8"},{name:"contribution",type:"uint256"},{name:"maxMembers",type:"uint8"},{name:"roundLength",type:"uint32"},{name:"grace",type:"uint32"},{name:"roundDeadline",type:"uint64"},{name:"currentRound",type:"uint8"},{name:"organizer",type:"address"},{name:"members",type:"address[]"},{name:"locked",type:"uint256[]"},{name:"allowance",type:"uint8[]"},{name:"paidThisRound",type:"bool[]"},{name:"misses",type:"uint8[]"},{name:"owed",type:"uint256[]"},{name:"credit",type:"uint256[]"},{name:"countsForTrust",type:"bool"},{name:"totalLocked",type:"uint256"},{name:"settleableAfter",type:"uint64"}]}],stateMutability:"view"},
  {type:"function",name:"grace",inputs:[],outputs:[{name:"",type:"uint32"}],stateMutability:"view"},
  {type:"function",name:"inviteHash",inputs:[],outputs:[{name:"",type:"bytes32"}],stateMutability:"view"},
  {type:"function",name:"isMember",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"bool"}],stateMutability:"view"},
  {type:"function",name:"join",inputs:[{name:"code",type:"bytes32"}],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"joinWithPermit",inputs:[{name:"code",type:"bytes32"},{name:"deadline",type:"uint256"},{name:"v",type:"uint8"},{name:"r",type:"bytes32"},{name:"s",type:"bytes32"}],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"leave",inputs:[],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"locked",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"maxMembers",inputs:[],outputs:[{name:"",type:"uint8"}],stateMutability:"view"},
  {type:"function",name:"memberAt",inputs:[{name:"i",type:"uint256"}],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"function",name:"memberCount",inputs:[],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"missCount",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"uint8"}],stateMutability:"view"},
  {type:"function",name:"organizer",inputs:[],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"function",name:"owed",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"paid",inputs:[{name:"",type:"uint256"},{name:"",type:"address"}],outputs:[{name:"",type:"bool"}],stateMutability:"view"},
  {type:"function",name:"paidCount",inputs:[],outputs:[{name:"",type:"uint8"}],stateMutability:"view"},
  {type:"function",name:"payBack",inputs:[],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"remove",inputs:[{name:"m",type:"address"}],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"roundContributions",inputs:[],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"roundDeadline",inputs:[],outputs:[{name:"",type:"uint64"}],stateMutability:"view"},
  {type:"function",name:"roundLength",inputs:[],outputs:[{name:"",type:"uint32"}],stateMutability:"view"},
  {type:"function",name:"settleRound",inputs:[{name:"round",type:"uint8"}],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"settleableAfter",inputs:[],outputs:[{name:"",type:"uint64"}],stateMutability:"view"},
  {type:"function",name:"start",inputs:[],outputs:[],stateMutability:"nonpayable"},
  {type:"function",name:"state",inputs:[],outputs:[{name:"",type:"uint8"}],stateMutability:"view"},
  {type:"function",name:"token",inputs:[],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"function",name:"totalLocked",inputs:[],outputs:[{name:"",type:"uint256"}],stateMutability:"view"},
  {type:"function",name:"trust",inputs:[],outputs:[{name:"",type:"address"}],stateMutability:"view"},
  {type:"function",name:"turnOf",inputs:[{name:"",type:"address"}],outputs:[{name:"",type:"uint8"}],stateMutability:"view"},
  {type:"event",name:"Activated",inputs:[{name:"roundDeadline",type:"uint64",indexed:false}],anonymous:false},
  {type:"event",name:"Cancelled",inputs:[],anonymous:false},
  {type:"event",name:"Completed",inputs:[],anonymous:false},
  {type:"event",name:"Contributed",inputs:[{name:"member",type:"address",indexed:true},{name:"round",type:"uint8",indexed:false},{name:"late",type:"bool",indexed:false}],anonymous:false},
  {type:"event",name:"CreditPaid",inputs:[{name:"member",type:"address",indexed:true},{name:"amount",type:"uint256",indexed:false}],anonymous:false},
  {type:"event",name:"Joined",inputs:[{name:"member",type:"address",indexed:true}],anonymous:false},
  {type:"event",name:"Left",inputs:[{name:"member",type:"address",indexed:true}],anonymous:false},
  {type:"event",name:"PaidBack",inputs:[{name:"member",type:"address",indexed:true},{name:"amount",type:"uint256",indexed:false}],anonymous:false},
  {type:"event",name:"PayoutHeld",inputs:[{name:"member",type:"address",indexed:true},{name:"round",type:"uint8",indexed:false},{name:"amount",type:"uint256",indexed:false}],anonymous:false},
  {type:"event",name:"RoundSettled",inputs:[{name:"round",type:"uint8",indexed:false},{name:"collector",type:"address",indexed:true},{name:"amount",type:"uint256",indexed:false},{name:"missed",type:"address[]",indexed:false}],anonymous:false},
  {type:"event",name:"Started",inputs:[{name:"order",type:"address[]",indexed:false}],anonymous:false},
  {type:"error",name:"AlreadyMember",inputs:[]},
  {type:"error",name:"AlreadyPaid",inputs:[]},
  {type:"error",name:"AlreadySettled",inputs:[]},
  {type:"error",name:"BadInvite",inputs:[]},
  {type:"error",name:"Full",inputs:[]},
  {type:"error",name:"NotMember",inputs:[]},
  {type:"error",name:"NotOrganizer",inputs:[]},
  {type:"error",name:"NothingOwed",inputs:[]},
  {type:"error",name:"OrganizerCannotLeave",inputs:[]},
  {type:"error",name:"PastGrace",inputs:[]},
  {type:"error",name:"RoundNotOpen",inputs:[{name:"opensAt",type:"uint64"}]},
  {type:"error",name:"SafeERC20FailedOperation",inputs:[{name:"token",type:"address"}]},
  {type:"error",name:"TooEarly",inputs:[{name:"settleableAfter",type:"uint64"}]},
  {type:"error",name:"TooFewMembers",inputs:[]},
  {type:"error",name:"WrongState",inputs:[{name:"current",type:"uint8"}]},
  {type:"error",name:"ERC20InsufficientBalance",inputs:[{name:"sender",type:"address"},{name:"balance",type:"uint256"},{name:"needed",type:"uint256"}]},
  {type:"error",name:"ERC20InsufficientAllowance",inputs:[{name:"spender",type:"address"},{name:"allowance",type:"uint256"},{name:"needed",type:"uint256"}]},
] as const;
