%%{init: {"theme":"base","themeVariables":{"xyChart":{"plotColorPalette":"#2B3CC4"}}}}%%
xychart-beta
  title "Adults in Nigeria using informal finance (%)"
  x-axis "EFInA survey year" [2016, 2018, 2020, 2023]
  y-axis "% of adults" 0 --> 60
  bar [29, 30, 33, 46]
